### ISSUE TITLE
Login exception

### ISSUE THREAD

**Issue by 1170634186** [AngeloTadeucci/Maple2#185]
![image](https://github.com/AngeloTadeucci/Maple2/assets/45306236/e238c50c-095d-4492-b450-c171e58686ad)

After starting the server, the login client message is abnormal, how should I solve this problem?

**Comment by Zintixx** [comment]
I can't see the error so I cannot help
![image](https://github.com/AngeloTadeucci/Maple2/assets/62830952/becbc259-a130-440e-9c01-3b57e06286be)

**Comment by 1170634186** [comment]
00:33:27.959 LoginSession [DBG] <1> Registered [0x0001] ResponseVersionHandler
00:33:27.971 LoginSession [DBG] <1> Registered [0x0003] LoginHandler
00:33:27.972 LoginSession [DBG] <1> Registered [0x0004] ResponseKeyHandler
00:33:27.972 LoginSession [DBG] <1> Registered [0x0009] CharacterManagementHandler
00:33:27.972 LoginSession [DBG] <1> Registered [0x000B] TimeSyncHandler
00:33:27.972 LoginSession [DBG] <1> Registered [0x0039] UgcHandler
00:33:27.972 LoginSession [DBG] <1> Registered [0x0056] LogSendHandler
00:33:27.972 LoginSession [DBG] <1> Registered [0x00B2] ServerEnterHandler
00:33:27.972 LoginSession [DBG] <1> Registered [0x00B7] SystemInfoHandler
00:33:28.356 LoginSession [INF] <1> LoginServer started on Port:20001
00:33:28.369     Lifetime [INF] <1> Application started. Press Ctrl+C to shut down.
00:33:28.371     Lifetime [INF] <1> Hosting environment: Production
00:33:28.371     Lifetime [INF] <1> Content root path: E:\Program Data\VS2022Demo\Maple2\Maple2.Server.Login
00:36:01.960 LoginSession [INF] <12> Login client connected: LoginSession from 127.0.0.1:60684
00:36:02.205 LogicalHandler [INF] <16> Start processing HTTP request POST http://127.0.0.1:21001/maple2.server.world.service.World/Channels
00:36:02.209 ClientHandler [INF] <16> Sending HTTP request POST http://127.0.0.1:21001/maple2.server.world.service.World/Channels
00:36:02.224     GrpcCall [ERR] <16> Error starting gRPC call.
System.Net.Http.HttpRequestException: Requesting HTTP version 2.0 with version policy RequestVersionOrHigher while unable to establish HTTP/2 connection.
   at System.Net.Http.HttpConnectionPool.ThrowGetVersionException(HttpRequestMessage request, Int32 desiredVersion, Exception inner)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
   at Grpc.Net.Client.Balancer.Internal.BalancerHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)
00:36:02.246     GrpcCall [INF] <16> Call failed with gRPC error status. Status code: 'Internal', Message: 'Error starting gRPC call. HttpRequestException: Requesting HTTP version 2.0 with version policy RequestVersionOrHigher while unable to establish HTTP/2 connection.'.
00:36:02.248 LoginSession [ERR] <16> Failed to login
Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: Requesting HTTP version 2.0 with version policy RequestVersionOrHigher while unable to establish HTTP/2 connection.", DebugException="System.Net.Http.HttpRequestException: Requesting HTTP version 2.0 with version policy RequestVersionOrHigher while unable to establish HTTP/2 connection.
   at System.Net.Http.HttpConnectionPool.ThrowGetVersionException(HttpRequestMessage request, Int32 desiredVersion, Exception inner)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
   at Grpc.Net.Client.Balancer.Internal.BalancerHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)")
   at Grpc.Net.Client.Internal.HttpClientCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Maple2.Server.World.Service.World.WorldClient.Channels(ChannelsRequest request, CallOptions options) in E:\Program Data\VS2022Demo\Maple2\Maple2.Server.Core\obj\Debug\net8.0\proto\world\WorldGrpc.cs:line 653
   at Maple2.Server.World.Service.World.WorldClient.Channels(ChannelsRequest request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken) in E:\Program Data\VS2022Demo\Maple2\Maple2.Server.Core\obj\Debug\net8.0\proto\world\WorldGrpc.cs:line 642
   at Maple2.Server.Login.Session.LoginSession.ListServers() in E:\Program Data\VS2022Demo\Maple2\Maple2.Server.Login\Session\LoginSession.cs:line 60
   at Maple2.Server.Login.PacketHandlers.LoginHandler.Handle(LoginSession session, IByteReader packet) in E:\Program Data\VS2022Demo\Maple2\Maple2.Server.Login\PacketHandlers\LoginHandler.cs:line 35
00:36:02.269      Session [INF] <16> Disconnected LoginSession from 127.0.0.1:60684
00:37:57.149 LoginSession [INF] <15> Login client connected: LoginSession from 127.0.0.1:60812
00:37:57.263 LogicalHandler [INF] <17> Start processing HTTP request POST http://127.0.0.1:21001/maple2.server.world.service.World/Channels
00:37:57.264 ClientHandler [INF] <17> Sending HTTP request POST http://127.0.0.1:21001/maple2.server.world.service.World/Channels
00:37:57.264     GrpcCall [ERR] <17> Error starting gRPC call.
System.Net.Http.HttpRequestException: Requesting HTTP version 2.0 with version policy RequestVersionOrHigher while unable to establish HTTP/2 connection.
   at System.Net.Http.HttpConnectionPool.ThrowGetVersionException(HttpRequestMessage request, Int32 desiredVersion, Exception inner)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
   at Grpc.Net.Client.Balancer.Internal.BalancerHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)
00:37:57.265     GrpcCall [INF] <17> Call failed with gRPC error status. Status code: 'Internal', Message: 'Error starting gRPC call. HttpRequestException: Requesting HTTP version 2.0 with version policy RequestVersionOrHigher while unable to establish HTTP/2 connection.'.
00:37:57.265 LoginSession [ERR] <17> Failed to login
Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: Requesting HTTP version 2.0 with version policy RequestVersionOrHigher while unable to establish HTTP/2 connection.", DebugException="System.Net.Http.HttpRequestException: Requesting HTTP version 2.0 with version policy RequestVersionOrHigher while unable to establish HTTP/2 connection.
   at System.Net.Http.HttpConnectionPool.ThrowGetVersionException(HttpRequestMessage request, Int32 desiredVersion, Exception inner)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
   at Grpc.Net.Client.Balancer.Internal.BalancerHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)")
   at Grpc.Net.Client.Internal.HttpClientCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Maple2.Server.World.Service.World.WorldClient.Channels(ChannelsRequest request, CallOptions options) in E:\Program Data\VS2022Demo\Maple2\Maple2.Server.Core\obj\Debug\net8.0\proto\world\WorldGrpc.cs:line 653
   at Maple2.Server.World.Service.World.WorldClient.Channels(ChannelsRequest request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken) in E:\Program Data\VS2022Demo\Maple2\Maple2.Server.Core\obj\Debug\net8.0\proto\world\WorldGrpc.cs:line 642
   at Maple2.Server.Login.Session.LoginSession.ListServers() in E:\Program Data\VS2022Demo\Maple2\Maple2.Server.Login\Session\LoginSession.cs:line 60
   at Maple2.Server.Login.PacketHandlers.LoginHandler.Handle(LoginSession session, IByteReader packet) in E:\Program Data\VS2022Demo\Maple2\Maple2.Server.Login\PacketHandlers\LoginHandler.cs:line 35
00:37:57.266      Session [INF] <17> Disconnected LoginSession from 127.0.0.1:60812

**Comment by 1170634186** [comment]
Is this abnormal due to a MapleShark2 startup abnormal?

**Comment by 1170634186** [comment]
![image](https://github.com/AngeloTadeucci/Maple2/assets/45306236/fedbf1c2-65ab-4ebc-973d-cfdca8f05c63)

**Comment by 1170634186** [comment]
Is it a reminder for me to install the .NET Framework runtime? But it doesn't tell me which version I should install, you know the problem

**Comment by 1170634186** [comment]
> 我看不到错误，所以我无能为力 ![图像](https://private-user-images.githubusercontent.com/62830952/339474072-becbc259-a130-440e-9c01-3b57e06286be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyOTcyMzQsIm5iZiI6MTcxODI5NjkzNCwicGF0aCI6Ii82MjgzMDk1Mi8zMzk0NzQwNzItYmVjYmMyNTktYTEzMC00NDBlLTljMDEtM2I1N2UwNjI4NmJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDE2NDIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlNzJhNGUwMTliYjVjNDhlYzgyZjU3YmNhMjkyMzk2ZmEyMGFiZWZjYTAwODUwY2QyNTk1NjQyZWVhYjliMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uxWgNpf5eWTkUzXKsMd-KM_vuKp4nRrqaRlli9FYD0w)

Brother, can you help me take a look

**Comment by Zintixx** [comment]
havent seen this issue. upon googling this may be the issue you're having:


https://stackoverflow.com/questions/66500195/net-5-grpc-client-call-throws-exception-requesting-http-version-2-0-with-versi

**Comment by 1170634186** [comment]
> 没有看到这个问题。在谷歌搜索时，这可能是您遇到的问题：
> 
> https://stackoverflow.com/questions/66500195/net-5-grpc-client-call-throws-exception-requesting-http-version-2-0-with-versi

Oh, thanks, from your reply I think this problem may not be caused by this program, I will check the environment of my computer

**Comment by 1170634186** [comment]
![image](https://github.com/AngeloTadeucci/Maple2/assets/45306236/ac74de0b-8c40-4c2a-93c1-edc10d43ce82)

Oh, it's actually because I use a VPN, and it's normal just after I quit the VPN

**Comment by 1170634186** [comment]
![Uploading image.png…]()

It's normal for the knight to start with the main line of the game

**Comment by 1170634186** [comment]
![image](https://github.com/AngeloTadeucci/Maple2/assets/45306236/4a943030-6063-48c6-9215-786ad3fc7c02)

It's normal for the knight to start with the main line of the game

**Comment by Zintixx** [comment]
Ok looks like this issue is resolved. I'm closing it now
